- name: Install nginx
  hosts: realworld-mongo
  become: true

  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present

  - name: Start NGiNX
    service:
      name: nginx
      state: started
